### ISSUE TITLE
PLEASE SEE THIS

### ISSUE THREAD

**Issue by OvOPlant** [Arjun99ab/ovo#12]
@Arjun99ab IM GROUNDED SO I CANT LOG INTO DISCORD SO CAN YOU PLEASE FOR ONCE SEE THESE FUCKING ISSUES IM POSTING I FIGURED IT WOULD BE OBVIOUS THAT THIS EXISTS BUT THEN AGAIN I STILL HAVE AN ISSUE OPEN FROM 1 WEEK AGO

**Comment by Arjun99ab** [comment]
i'm not working on dimensions rn

**Comment by OvOPlant** [comment]
i was going to ask if i could know how you got all the dimensions files.

**Comment by Arjun99ab** [comment]
yeah i don't specifically remember how - i think I lost what i wrote for it. I do remember it was horribly inefficient which is something i'll try to fix when im bugfixing dimensions

**Comment by OvOPlant** [comment]
if you ever do fix it, would i be able to know how

**Comment by Arjun99ab** [comment]
idk

**Comment by OvOPlant** [comment]
wdym you dont know.
